kind: Deployment  
apiVersion: apps/v1  
metadata:  
  name: whoami
  labels:
    name: whoami
spec:  
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: containous/whoami
          ports:
            - name: web
              containerPort: 80
---
kind: Service  
apiVersion: v1  
metadata:  
  name: whoami
spec:  
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    name: whoami
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whoami-traefik-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: whoami
          servicePort: http
